version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-troque-aqui-senha-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-evolution}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@exemplo.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-troque-aqui-senha-pgadmin}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "4000:80"
    networks:
      - evolution-net
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - evolution-net

  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution_api
    restart: always
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    ports:
      - "8082:8080"
    networks:
      - evolution-net
    depends_on:
      - postgres
      - redis

  # Caso  queira subir a API junto com os outros containers,
  # basta descomentar o codigo abaixo.
  #
  # api-whatsapp:
  #   image: maven:3.9-eclipse-temurin-21
  #   container_name: api_whatsapp
  #   working_dir: /workspace
  #   volumes:
  #     - ../api-springBoot:/workspace
  #   command: mvn spring-boot:run
  #   environment:
  #     SERVER_PORT: 8081
  #     EVOLUTION_BASE_URL: http://evolution-api:8080
  #     EVOLUTION_INSTANCE: Gerenciador_containeres
  #     EVOLUTION_URL: http://evolution-api:8080/message/sendText/Gerenciador_containeres
  #     EVOLUTION_TOKEN: troque-aqui
  #     DOCKER_HOST: tcp://host.docker.internal:2375
  #     WHATSAPP_ADMIN: 556599999999
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - evolution-net
  #   depends_on:
  #     - evolution-api

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
  evolution_instances:

networks:
  evolution-net:
    driver: bridge
